### ISSUE TITLE
sf2 profiler - no data

### ISSUE THREAD

**Issue by npanau** [pomm-project/pomm-bundle#47]
Hi,

I have the latest Pomm2 configured & well operating.
Except for the profiler, that never show a query nor a query count.
![capture d ecran 2015-12-22 a 09 46 23](https://cloud.githubusercontent.com/assets/458684/11951405/f2c59942-a890-11e5-95f5-1e17fdf5dac7.png)

I followed the documentation, any clue on what could be missing?

Thanks

**Comment by stood** [comment]
Yes we work on this bug : https://github.com/pomm-project/pomm-symfony-bridge/issues/20

**Comment by npanau** [comment]
Ok thanks, FYI, it is on SF2.8.

**Comment by chanmix51** [comment]
Weird, I don't have the problem with Silex. @sanpii ?

**Comment by sanpii** [comment]
I made a rapid `composer update` on my [symbiose project](https://github.com/sanpii/symbiose) and I have a log. Do you use the query manager?

![screen shot 2015-12-22 at 23 54 17](https://cloud.githubusercontent.com/assets/113045/11967948/5b0c85bc-a907-11e5-9d60-51de960aab54.png)

**Comment by npanau** [comment]
Not yet ; I'm on describing CRUD operations, I only use [default queries](https://github.com/pomm-project/ModelManager/blob/master/documentation/model_manager.rst#default-queries) for now (eg findAll(), findByPK, createAndSave()...)

**Comment by chanmix51** [comment]
These queries should show up in the profiler. Can you show us a controller where those queries are used with a shot of the profiler of the same URL ?

**Comment by npanau** [comment]
Sure : 
```php
    /**
     * Edition ...
     */
    public function editAction($id, Request $request)
    {
        $user = $this
            ->container->get('pomm')['my_db']
            ->getModel(UserModel::class)
            ->findByPK([
                'id' => $id
            ]);
    //...
```
![capture d ecran 2015-12-23 a 10 46 13](https://cloud.githubusercontent.com/assets/458684/11974227/6de5ee8e-a962-11e5-8036-339f10385970.png)
(is that what you meant for the shot?)

**Comment by chanmix51** [comment]
You have a findByPK in a edit url ? I ask to understand if you have been redirected or not.

**Comment by npanau** [comment]
Yep ; I have not been redirected, 0 is the PK of this entry. Btw, the query does return me the correct results, and the Flexible entity is hydrated.

**Comment by chanmix51** [comment]
I can't reproduce the bug. I installed a fresh version of sf 2.8 using symfony’s installer, setup as indicated on pomm-bundle’s README and I could see the queries in the profiler.

**Comment by npanau** [comment]
ok ; mine is an updated version, not a fresh install ; this is probably due to my setup. I'll try to reinstall everything and dig in this issue.

**Comment by SebLours** [comment]
Hy all,

For me on a fresh install of Symfony 3.0.0, i don't have any data into the pomm profiler.
I can get some pomm data collecting like this:
``` php
$session = $this->get('pomm.default_session');

$dataCollector = $this->get('pomm.data_collector');

$session
    ->getClientUsingPooler('listener', 'query')
    ->attachAction([$dataCollector, 'execute'])
;

$crews = $session
    ->getQueryManager()
    ->query($sql)
;
```
After some code inspection, i think that the data collector service is created after the Pomm session creation. The session builder post configuration is never called.

**Comment by stood** [comment]
https://github.com/pomm-project/pomm-bundle/pull/48

**Comment by Nedeas** [comment]
Hi,
I work with npanau and I search the origin of this bug.
In symfony 2.8.2, when I add custom UserProvider (used Pomm) in security, the Pomm profiler doesn't work. 
If I remove then, Pomm profiler works.

When Pomm profiler doesn't work, I have this in log :
```
17:56:23
app	Pomm: ListenerPooler: notification received.
Context: { "receivers": "query:pre" }
17:56:23
app	Pomm: ListenerPooler: notification received.
Context: { "receivers": "query:post" }
```

**Comment by chanmix51** [comment]
These are the notification emitted by Pomm before and after a query is sent. You should also have these lines when the profiler works.

**Comment by stood** [comment]
Because UserProvider with loadUserByUsername will use Pomm before the listener DatabaseDataCollector that start

**Comment by Nedeas** [comment]
@chanmix5 : Yes but I have always 0 query in debug bar.
@stood : I have a query in controller for test and I have 0 query in debug bar.

**Comment by stood** [comment]
@Nedeas yes I have the same pb because pomm is started with UserProvider and Listener for dataCollector after.

**Comment by chanmix51** [comment]
How can we fix that ?

**Comment by sanpii** [comment]
https://github.com/symfony/symfony/issues/17612

**Comment by stof** [comment]
IMO, the issue is that the instantiation of the profiler collector is the place where PommBundle is registering the profiler in the connection. This expects the profiler collector to be instantiated before any request is made with Pomm. But there is no such guarantee in Symfony (services are instantiated the first time they are needed in some object graph, so there is exactly no guarantee about when this happens). Registering the profiling in the connection should be done in the instantiation of the connection service, so that it is done as soon as the connection is needed to ensure it is done.

**Comment by chanmix51** [comment]
@stof sorry to ask but I do not understand what you mean by «Registering the profiling in the connection». What connection are you mentioning here ?

**Comment by npanau** [comment]
Hi there,

Good news : since my last composer update, the profiler is showing :)
Here's the references : 
 ```
 - Updating pomm-project/pomm-symfony-bridge dev-master (691df46 => f168161)
    Checking out f168161ea1c5ba5e12e137a58f814b1769147f70

  - Updating pomm-project/pomm-bundle dev-master (d967d19 => 7e60325)
    Checking out 7e60325d3a85068c223f5def5d87f7984b8d93d9

  - Updating pomm-project/foundation 2.0.x-dev (6435ae2 => 1438035)
    Checking out 1438035a643b1bd6fdd572ec22951adb6e382b54
```
Good job!

**Comment by stof** [comment]
@chanmix51 replace "connection" by "session" to use the Pomm namings. But this was solved by https://github.com/pomm-project/pomm-symfony-bridge/pull/24 and https://github.com/pomm-project/pomm-bundle/pull/50

**Comment by stood** [comment]
@npanau plz close if it's ok

**Comment by rdavaillaud** [comment]
I still have the same bug with latest stable version of pomm bundles and Symfony 3.1.5).
I also have a custom UserProvider using pomm, and no quey in the profiler.

I am using theodo-evolution/session-bundle to share user cookie with sf1 and load the user from the cookie's user id.
Using Symfony Guard as authentication mecanism.
```php
<?php
...
use Symfony\Component\Security\Guard\AbstractGuardAuthenticator;


class CookieLoginAuthenticator extends AbstractGuardAuthenticator
{
    private $router;
    private $pomm;

    public function __construct(\PommProject\Foundation\Pomm $pomm, RouterInterface $router)
    {
        $this->router = $router;
        $this->pomm = $pomm;
    }

    public function getCredentials(Request $request)
    {
        $guardUser = $request->getSession()->getBag('symfony/user/sfUser/attributes')->get('sfGuardSecurityUser');

        return $guardUser;
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $userId = $credentials['user_id'];
        $user = $this->pomm['lpdipro']
                    ->getModel('\AppBundle\Security\User\LPdIUserModel')
                    ->findByPK(['id' => (int)$userId]);

        if (is_null($user)) {
            throw new UsernameNotFoundException(
                sprintf('User id "%s" does not exist.', $userId)
            );
        }

        return $user;
    }
...
```

When no user is authentified (profiler showing anon.), I've got the correct query count, when the user is authentified, no query.
